### ISSUE TITLE
Wiki Addition: Datamining Pipeline Documentation

### ISSUE THREAD

**Issue by elfeck** [SGpp/SGpp#106]
Hello SG++ developers, 

in the past weeks I worked on the datamining pipeline documentation, in particular documenting the many JSON parameters that are available to configure the pipeline.

Following the new workflow for wiki changes I manually forked the SGpp.wiki repo and you can review the changes [in my fork](https://github.com/elfeck/SGpp-wiki/tree/pipeline_doc). In particular the files [Datadriven-datamining-pipeline.md](https://github.com/elfeck/SGpp-wiki/blob/pipeline_doc/Datadriven-datamining-pipeline.md) and [Datadriven-datamining-pipeline-configuration.md](https://github.com/elfeck/SGpp-wiki/blob/pipeline_doc/Datadriven-datamining-pipeline-configuration.md).

Originally this doc was written as static doxygen documentation hence the HTML tables and so on. I made several changes to have a nicer result in github markdown, but at certain points the formatting might not be optimal.

I hope I made no mistakes with the (new) links in _Sidebar.md and in the other new files. I cannot test these changes with my forked repo.

This is supposed to be a first version which I will continuously improve.

**Comment by krsgpp** [comment]
I just edited our wiki and incorporated the datamining pipeline pages.
