### ISSUE TITLE
Reference to GridType in AlgorithmAdaBoostBase and others

### ISSUE THREAD

**Issue by pfluegdk** [SGpp/SGpp#113]
There are several places such as in AlgorithmAdaBoostBase, AlgorithmAdaBoostIdentity, ... where the enum sgpp::base::GridType is not used but where, instead, new ids are given and used for different grid types. They should be replaced by the proper names.

**Comment by spc90** [comment]
These two particular classes (AlgorithmAdaBoostBase and AlgorithmAdaBoostIdentity) have been fixed and a pull request draft (#155 ) has been made. I have left the pull request in draft mode for now, as there is no straight-forward way to check if the same wrong usage of a "grid type" variable does not appear somewhere else. So far, after searching by multiple keywords that would make sense, I have not found other files that have a similar issue.

@pfluegdk if you are satisfied with the current state, and/or other people don't find other files with the same problem in the next couple of days, I think it's safe to change the status of the pull request to active and go forward with merging this.
