### ISSUE TITLE
DataMatrix::getRow and DataMatrix::getCol do not check for out of bounds parameters

### ISSUE THREAD

**Issue by Milchshakee** [SGpp/SGpp#126]
It is possible to run the following code without errors even though we read out of bounds data:

```c++
#include <sgpp_base.hpp>

int main() {
  sgpp::base::DataMatrix matrix(2,2);
  sgpp::base::DataVector v(2);
  matrix.getCol(3, v);
  return 0;
}
```

Same thing works with `DataMatrix::getRow`.

**Comment by leiterrl** [comment]
This could actually be intended by design. Performing an if check every time you get some data from the matrix might have a noticeable impact on performance. For reference std::vector also doesn't perform out-of-bounds check when using the [] operator.

**Comment by spc90** [comment]
Agreed with @leiterrl that we probably shouldn't have checks there, as std::vector also does not provide such a thing. As a rule, I think it makes sense for setters to have bound checks, and not for getters. Whether or not this design choice is actually enforced across all methods, well, that's another matter :)

**Comment by valentjn** [comment]
Yeah, this is by design. Eons ago, when `DataVector` didn't derive from `std::vector`, `DataVector::operator[]` didn't check for bounds either. One could think about adding that to the docs somewhere, but that would be a different issue.
