### ISSUE TITLE
installation layout

### ISSUE THREAD

**Issue by jschueller** [SGpp/SGpp#129]
sgpp does not install as I'd expected:
- the Python bindings folder pysgpp does not get installed into PREFIX (\$PREFIX/lib/pythonx.y/site-packages/pysgpp on unix or \$PREFIX/Lib/site-packages on win32)
- c++ libs are installed in a \$PREFIX/lib/sggp subfolder (and cannot be loaded by default)

**Comment by leiterrl** [comment]
Regarding the python bindings there is an experimental setup.py supplied in the root folder. This means you can install the bindings using pip
`pip install . --user`
with all the usual functionality of pip.

The PREFIX usage is indeed not intuitive. After some digging I found that for now you can directly specify the "LIBPATH" variable to set the install directory of the sgpp libraries. In the future I agree that this behaviour should be changed.
