### ISSUE TITLE
Replace include guards with #pragma once

### ISSUE THREAD

**Issue by Milchshakee** [SGpp/SGpp#138]
It's possible to use this regex: ``#ifndef (.*)\n#define (.*)\n((.|\n)*)#endif.*\n`` and replace with ``#pragma once\n$3``.

**Comment by MichaelReh** [comment]
At the Coding Days Summer 2021 it was decided that we generally prefer #pragma once but we do not enforce it. So when writing new code use #pragma once, but we won't modify old code. See the [developer guidelines](https://github.com/SGpp/SGpp/wiki/DeveloperGuidelines)
