### ISSUE TITLE
Duplicate code in misc and pde module

### ISSUE THREAD

**Issue by leiterrl** [SGpp/SGpp#140]
It seems that the following files are completely identical:

misc/src/sgpp/misc/pde/algorithm/UpDownOneOpDimEnhanced.cpp
pde/src/sgpp/pde/algorithm/UpDownOneOpDimEnhanced.cpp

maybe this was just left over when moving stuff out of the misc module

**Comment by valentjn** [comment]
Yes, I think in 58bb9f850 we copied the misc file to pde, but we forgot to delete the misc one.
