### ISSUE TITLE
Usability of Combigrid Module

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [SGpp/SGpp#141]
We would like to improve the usability of the combigrid module. This issue here to collect different aspects, starting with:

## Analysis of Issues
  * Interface: no access to grids themselves (always `operators` with very specific class names)
  * So many wrapper classes

## Desired basic interface functionality for grids
  * generate grids
  * access on grids (also interpolated values)
  * conversion to sgpp grids

## What we'd like to keep from the current implementation
  * different bases in different directions
  * the functionality in the `common` folder: index iterators etc., especially those used from LevelManager (generate combischemes by defining grids that should be in the scheme)

Feel free to add to the discussion - this will likely be addressed in the medium run.

**Comment by freifrauvonbleifrei** [comment]
### Comparison to other interfaces
  * Tasmanian SG package https://tasmanian.ornl.gov/
    ```
    grid.makeGlobalGrid ( dimension, outputs, level, TasGrid::type_level,
    TasGrid::rule_clenshawcurtis );
    ```
  * SPINTERP http://people.math.sc.edu/Burkardt/m_src/spinterp/help/spinterp.html
    ```
    options = spset('DimensionAdaptive','on',...
                    'DimadaptDegree', 1, ...
                    'FunctionArgType','vector',...
                    'RelTol', 1e-3,...
                    'MaxPoints', 40000);
    z1 = spvals(@trid, d, range, options)
    ```
  * Garcke: https://github.com/jgarcke/sparse-grid-py/blob/master/pysg.py
    ```
    sg = pysg.sparseGrid(3,3)
    sg.generatePoints()
    ```

  * Sparse Grids Matlab Kit https://sites.google.com/view/sparse-grids-kit
    ```
    S_doub=tensor_grid(N,lev2knots_doubling(ii),knots);
    ```
  * SGpp
    ```
    auto grid = sgpp::base::Grid::createModLinearGrid(dimensions);
    auto& storage = grid->getStorage();
    auto generator = sgpp::base::HashGenerator();
    ```
    or
    ```
    sgpp::base::ModBsplineGrid grid(d, p);
    sgpp::optimization::IterativeGridGeneratorRitterNovak gridGen(f, grid, N, gamma);
    gridGen.generate();
    ```

**Comment by krsgpp** [comment]
As for generation of component-grids, you might want to look at https://github.com/SGpp/SGpp/blob/e4aa4807419b9e2b05b5d1e9c03a92b6753e8349/base/src/sgpp/base/grid/generation/GridGenerator.hpp#L111

**Comment by krsgpp** [comment]
Also, a simple implementation for die Combination Technique can be found here:
https://github.com/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/algorithm/CombiScheme.hpp

**Comment by freifrauvonbleifrei** [comment]
cf. Julian's efforts on branch `feature-combigrid` https://github.com/SGpp/SGpp/tree/feature-combigrid

**Comment by valentjn** [comment]
There is now a draft PR #176 for a redesigned combigrid module. Any help is greatly appreciated.
