### ISSUE TITLE
Fix documentation of gettingStarted.py (Start Here) 

### ISSUE THREAD

**Issue by pfluegdk** [SGpp/SGpp#142]
The generated doxygen page is broken, see
http://sgpp.sparsegrids.org/example_gettingStarted_py.html
at the bottom

**Comment by freifrauvonbleifrei** [comment]
Fix: if examples work, remove all `#` in those lines.

But I am now getting an error when trying to run the gettingStarted example: 
```
Traceback (most recent call last):
  File "gettingStarted.py", line 16, in <module>
    from pysgpp.extensions.datadriven.uq.plot.colors import initialize_plotting_style, \
  File "/data/scratch/pollinta/SGpp/lib/pysgpp/extensions/datadriven/uq/plot/__init__.py", line 48, in <module>
    from pysgpp.extensions.datadriven.uq.parameters.plot.plotGrid import plotGrid
ImportError: No module named 'pysgpp.extensions.datadriven.uq.parameters.plot'
```
is this being moved around?

**Comment by valentjn** [comment]
@freifrauvonbleifrei That line was introduced in 062dddb, no moving around. Probably no one has tested the examples since then?

**Comment by freifrauvonbleifrei** [comment]
@valentjn looks like it!
