### ISSUE TITLE
Wiki: Linux compilation Scons additional flags

### ISSUE THREAD

**Issue by hirschsn** [SGpp/SGpp#146]
Your wiki (https://github.com/SGpp/SGpp/wiki/Linux-(GCC-Clang-ICC)#compilation-with-scons) says:
`scons CPPFLAGS='-g -O0'`

But scons does not accept this. It needs to be:
`scons CPPFLAGS='-g,-O0'`

Because the `multiParamConverter` in Helper.py is defined as:
```
def multiParamConverter(s):
  return s.split(",")
```

**Comment by MichaelReh** [comment]
Corrected
