### ISSUE TITLE
Python Datadriven UQ modules

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [SGpp/SGpp#148]
Follow-up on #142 :

there seems to be some python code that has additional `.parameters` in the module path, eg:
https://github.com/SGpp/SGpp/blob/master/datadriven/python/uq/plot/__init__.py

```
from pysgpp.extensions.datadriven.uq.parameters.plot.plotGrid import plotGrid
```
should be
```
from pysgpp.extensions.datadriven.uq.plot.plotGrid import plotGrid
```

**Comment by valentjn** [comment]
(Issues should not be closed before PRs fixing them are merged.)
