### ISSUE TITLE
Travis CI's time limit exceeded

### ISSUE THREAD

**Issue by valentjn** [SGpp/SGpp#173]
Some Travis CI jobs currently exceed the time limit of 50 minutes, which makes it hard to merge PRs. There are at least two solutions for this (which are not mutually exclusive):
* Cut down the compile time
* Split up the jobs

Regarding the first point, we could save a lot of time in the unit tests. The last successful `master` build of Travis CI took 711s (11m51s) in the unit tests, of which were 45% in `datadriven`, 22% in `solver`, 15% in `pde`, and 9% in `optimization` and `combigrid` each. (`base` is only 1%. Values don't sum up to 100% due to rounding errors.)

The second point could be a bit difficult as the different modules/parts depend on each other...

**Comment by valentjn** [comment]
Travis is not a subset of the Jenkins jobs. Travis tests for different user-realistic scenarios with a varying set of installed dependencies and supplied flags on a vanilla Ubuntu VM. So simply deactivating Travis is not an option.

**Comment by krsgpp** [comment]
Concerning the split, could we have one job that runs only the datadriven tests/examples and one job that runs all the other tests/examples but not the ones from datadriven?

**Comment by MichaelReh** [comment]
At the Codings Days Summer 2021 we moved from Travis to GitHub Actions, so this can be closed.
