### ISSUE TITLE
gridConfig struct contains uninitialized attributes

### ISSUE THREAD

**Issue by elfeck** [SGpp/SGpp#174]
While fixing some issues related to the datamining pipeline I noticed, that many attributes in
[GeneralGridConfiguration](https://github.com/SGpp/SGpp/blob/master/base/src/sgpp/base/grid/Grid.hpp#L83) and [AdaptivityConfiguration](https://github.com/SGpp/SGpp/blob/master/base/src/sgpp/base/grid/Grid.hpp#L130) contain uninitialized attributes.

This is bad because it leads to undefined behavior if other code accesses these attributes relying on some sort of default value. Such a default value may or may not be sensible but I think undefined behavior is much worse than a non-sense default value.

I would like to set default values for all these config-struct-attributes. This was already implemented in the config structs in the datadriven module but before changing `base` I would like to have the go-ahead and maybe suggestions for the values to set.

@valentjn @krsgpp

**Comment by valentjn** [comment]
As seen in #172, missing defaults can cause problems. It doesn't look that bad here though, many members already have defaults. The rest can probably just be set to 0 (or 0.0 for the threshold or false for the refinement type). Application code is supposed to overwrite them anyway, this would just be to prevent UB and to signal the user "this member is not set yet." It's a bit harder to tell if there are already some more reasonable values in there.

But you could use anything, really. So if you want to use meaningful values, go ahead.

**Comment by elfeck** [comment]
I added default values for all struct members that are relevant for the pipeline and documented as such in the wiki in [this commit](https://github.com/elfeck/SGpp/commit/8b67977cf9bff9f2198c91d6228f734e0825715d). It includes default values for `GeneralGridConfiguration` and `AdaptivityConfiguration`.

The only value that remains uninitialized now is `levelVector_`. This attribute is actually parsed by the pipeline config parsing system but not yet documented. I'm not entirely sure yet how and where it is used.

The commit linked above also deletes [BatchConfiguration.hpp](https://github.com/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/configuration/BatchConfiguration.hpp) since it is used nowhere (as far as I can tell; compiles successfully without it).

Any comments are appreciated.

**Comment by krsgpp** [comment]
I expect levelVector_ to be handeld by Kilian Glas soon in an pull request. So no need to worry about it now.

**Comment by valentjn** [comment]
`levelVector_` is already initialized by its default constructor as the empty `vector`. Whether that’s desirable or not is another story.

**Comment by elfeck** [comment]
Note: At master RegularizationConfiguration now has uninitialized attributes again.

**Comment by elfeck** [comment]
With the merge of #178 this can be closed. I fear with new configuration people will start to introduce new uninitialized attributes but at least `gridConfig` and `adaptivityConfig` (main concern of this issue) are dealt with now
