### ISSUE TITLE
Issues Installing on Windoze

### ISSUE THREAD

**Issue by EDShapiro** [SGpp/SGpp#191]
I have set all paths in my environmental variables to appropriate directories, and when I run:
python setup.py install --EvanD
from cmd I get the following error message:
Traceback (most recent call last):
  File "setup.py", line 45, in <module>
    with open(initFile, "w") as f:
IOError: [Errno 2] No such file or directory: 'lib\\pysgpp\\__init__.py'
I looked at the setup.py file, and it seems like the script is supposed to create this directory. I am not sure what is going on or how to fix this.

**Comment by valentjn** [comment]
@EDShapiro This is too little information to reproduce this. (What steps have you performed? Which SG++/Python/Windows versions? Which flags did you use during compilation? Etc.)

But I think you're using v3.2.0 and this should already be fixed in the current `master`. Can you try that? Thank you!

**Comment by EDShapiro** [comment]
Sorry, I am new to this. 
I am using Windows 10.
I am using the SG++ v3.2.0 source code. Is this pre-compiled, or do I need to this compile myself?
I have followed the steps outlined in the installation instructions that are included in the source code.
Thanks,
Evan

**Comment by valentjn** [comment]
@EDShapiro Yes, you need to compile it first. There are multiple options on Windows: MinGW, WSL (Windows Subsystem for Linux), or a Linux virtual machine. [For MinGW, please see the Wiki for instructions.](https://github.com/SGpp/SGpp/wiki/Windows-(MinGW))

**Comment by pfluegdk** [comment]
> I am using Windows 10.
> I am using the SG++ v3.2.0 source code. Is this pre-compiled, or do I need to this compile myself?
> I have followed the steps outlined in the installation instructions that are included in the source code.
> Thanks,
> Evan

@EDShapiro Did compiling help?
