### ISSUE TITLE
Reading in CSV files via DataSourceBuilder

### ISSUE THREAD

**Issue by uselessisety** [SGpp/SGpp#2]
Hi,
I experienced a problem with reading in CSV files using DataSourceBuilder. ARFF Files seem to work fine, but comma separated value files of this format
 
x0,x1,x2,x3,x4,y
0.220847790771,0.517040101927,0.19956562731,0.639407139068,1.46804001503
0.0838406379871,0.295235516856,0.272006109762,0.310603660615,1.52258099856
...

If I try to read in a file like this e.g. with _sgpp/datadriven/examples/CrossValidationExample_ it results in a segfault. For ARFF files like the _sgpp/datadriven/tests/data/friedman3_10k_train.arff_ file it works fine. I also tried without the header line in the CSV file and whitespace separator. Am I using it wrong/have the wrong CSV format (the needed format does not seem to occur in the documentation, at least I did not find it) or is this an issue with the DataSourceBuilder?

Best,
Bastian

**Comment by pfluegdk** [comment]
Thanks for pointing that out. We'll add explanations for the next release.
