### ISSUE TITLE
MinGW and localtime_r

### ISSUE THREAD

**Issue by MichaelReh** [SGpp/SGpp#226]
I'm currently trying to build the new release SG++ 3.3 for Matlab on Windows.
But MinGW does not support localtime_r used in [BoHyperparameterOptimizer's](https://github.com/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/datamining/modules/hpo/BoHyperparameterOptimizer.cpp) writeToFile (line 40).
Is writing the local time to the file necessary here at all or can we just delete it?

**Comment by leiterrl** [comment]
This can be circumvented by setting CPPDEFINES="_POSIX_C_SOURCE=1" on the scons command. I'm not sure where to put this information though as this is definitely not trivial to find out. Regarding the necessity of using this function in the first place I have no idea tbh.

**Comment by MichaelReh** [comment]
CPPDEFINES="_POSIX_C_SOURCE=1" is not working for me. Still the same error.

**Comment by MichaelReh** [comment]
CPPDEFINES=_POSIX_C_SOURCE=1 (no quotation marks) and a fresh download of SG++'s master did the trick. I succesfully compiled SG++ 3.3 for Windows including Matlab.
