### ISSUE TITLE
Missing extensions directory (compiling with GCC under Linux)

### ISSUE THREAD

**Issue by PeterDomanski** [SGpp/SGpp#245]
After installing the recommended and the optional packages and dependencies, the compilation with SCons worked without errors. Moreover, all unit-tests ran without any failures. If we now try to import the pysgpp package in Python, an error message occurs that says that the "SGpp/lib/pysgpp/extensions" directory was not created. Thus, ". import extensions" in SGpp/lib/pysgpp/__init__.py fails. One can manually solve this issue by copying the extensions directory from "build/lib/pysgpp" into "lib/pysgpp".

**Comment by spc90** [comment]
Seems to have been fixed in the latest master version.
