### ISSUE TITLE
GitLab-GitHub users & merges management / sggp-dev und sgpp-users Mailing lists

### ISSUE THREAD

**Issue by valentjn** [SGpp/SGpp#25]
In GitLab by @pfluegdk on Aug 2, 2016, 15:31

sgpp@ipvs auf Mailman überführen?
sgpp-users einrichten (Infrastruktur)

**Comment by valentjn** [comment]
In GitLab by @spc90 on Aug 21, 2018, 10:53

changed title from **sggp-dev und sgpp-users Mailing lists** to **{+GitLab-GitHub users & merges management / +}sggp-dev und sgpp-users Mailing lists**

**Comment by pfluegdk** [comment]
We have now a mailman mailing list: SGpp@mailman.informatik.uni-stuttgart.de
Current decision is to have a joint mailing list for users and developers. If that causes too much traffic, we will split. Until then: united we go :-)
