### ISSUE TITLE
pysgpp does not work on Windows with Python 3.8+

### ISSUE THREAD

**Issue by crschnick** [SGpp/SGpp#253]
Python 3.8 changed the way how DLLs are loaded. (See [here](https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew))

This means that it is not enough to have the required sgpp DLLs on the PATH, it is also required to explicitly add DLL search directories in Python.

**Comment by leiterrl** [comment]
Thanks for the report. However, this is a duplicate of #220 so I'm closing this issue.
