### ISSUE TITLE
Compilation problem newer versions because of depreceated "distutils"

### ISSUE THREAD

**Issue by benjione** [SGpp/SGpp#263]
Error output in the compilation
```
Info: pythonpath = <string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
/usr/include/python3.10
Checking for C++ header file Python.h... no
```
caused by line 313 in SGppConfigure.py:
```
pythonpath = getOutput(["python3", "-c",
          "import distutils.sysconfig; "
          "print(distutils.sysconfig.get_python_inc())"])
```
Workaround:
open python and run
```
import distutils.sysconfig; 
print(distutils.sysconfig.get_python_inc())
```
and modify the variable `pythonpath` in line 313 in SGppConfigure:
```
pythonpath = "$(output)"
```
in my case:
```
pythonpath = "/usr/include/python3.10"
```

**Comment by G-071** [comment]
It seems the recommended way forward is to use sysconfig instead. That should be mostly straightforward as only SGppConfigure.py is affected. However, apparently moving from distutils to sysconfig can be a bit quirky on some platforms ([for example here](https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1940705)). 

I think it is best to address this issue during the next coding days when we can ensure that the migration is working on all the different platforms that people use (though we should not wait too long as the change becomes mandatory with Python 3.12). @pfluegdk: This should be added to the todo items for the next coding days!

To keep things running until then, I have added a workaround to the SGpp Spack package (see linked PR above) which automatically applies a workaround patch when using Python 3.10 and 3.11 (Python version <= 3.9 do not yet have the troublesome deprecation warning). This works for the master branch, as well as for the current and older SGpp releases.
