### ISSUE TITLE
SurplusCoraseningFunctor issue

### ISSUE THREAD

**Issue by uselessisety** [SGpp/SGpp#3]
Hi,

I have found an issue with the `SurplusCoarseningFunctor`. If you want to coarsen only w.r.t. the threshhold, you could easily do that by passing `std::numeric_limits<int>::max()` as `removements_num` parameter and expect it to work in the same way as `SurplusRefinementFunctor`. 

However in the `HashCoarsening::free_coarsen_NFirstOnly` method, a `GridPointPair` array of size `removements_num` is allocated which leads to a bad_alloc in this case. However, since you cannot coarsen any more points than points available in the grid anyhow, one could easily circumvent this for the user by changing the output of `SurplusCoarseningFunctor::getRemovementsNum()` to 
`min(this->removements_num, alpha.size())`.

**Comment by valentjn** [comment]
Thanks for the suggestion. I think the current implementation implicitly assumes `removements_num` to be smaller or equal to the grid size. It's not really communicated in the docs though. Alternatively (or additionally) to your suggested fix, you could directly clamp `remove_num` in `HashCoarsening::free_coarsen_NFirstOnly`; this way, it would also work for other coarsening functors, which might be user-defined. Either way, we should be able to fix this in the next release.

**Comment by valentjn** [comment]
This should be fixed via #71 that was moved over from GitLab.
