### ISSUE TITLE
HierarchisationSLE doesn't work with BoundingBox

### ISSUE THREAD

**Issue by valentjn** [SGpp/SGpp#34]
In GitLab by @valentjn on Sep 5, 2016, 10:27

`HierarchisationSLE` currently uses `gridStorage.getCoordinate` for evaluation of the basis functions at the grid points. This is wrong as `getCoordinate` returns coordinates in the bounding box, but `eval` expects them to be in the unit interval.

**Comment by valentjn** [comment]
In GitLab by @spc90 on Mar 15, 2017, 13:42

I created a new function that uses the `transformPointToUnitCube` function when needed, so as to give `eval` the right parameter coordinates.

**Comment by spc90** [comment]
@valentjn This has been solved by me a while back already (see f1fd57e8fc8afac7af44b9ad4a78b6b1fbc82999).
