### ISSUE TITLE
LevelManager::addRegularLevelsParallel  error

### ISSUE THREAD

**Issue by valentjn** [SGpp/SGpp#61]
In GitLab by @bountons on Jun 20, 2018, 01:33

1//3 times the function will result in segmentation fault / bad_alloc / double free or corruption (out) Aborted (core dumped).

**Comment by valentjn** [comment]
In GitLab by @valentjn on Jun 20, 2018, 07:56

A minimal example would be great.

**Comment by valentjn** [comment]
In GitLab by @bountons on Jun 20, 2018, 10:02

I can recreate the issue in combigrid/examples/interpolation.cpp by replacing line 165 " levelManager->addRegularLevels(maxLevelSum);" with "levelManager->addRegularLevelsParallel(maxLevelSum,2);"

**Comment by valentjn** [comment]
In GitLab by @valentjn on Jun 20, 2018, 10:29

Can confirm. Looks like a race condition to me. The error vanishes when running with `valgrind`.

**Comment by leiterrl** [comment]
Closed since the functionality in question does not exist anymore.
