### ISSUE TITLE
Output of std::vectors/DataVectors is broken

### ISSUE THREAD

**Issue by valentjn** [SGpp/SGpp#64]
In GitLab by @valentjn on Aug 15, 2018, 14:42

The following code is currently in `HashGenerator.hpp`:

```c++
template <typename T>
std::ostream& operator<<(std::ostream& out, const std::vector<T>& v) {
  if (!v.empty()) {
    out << '[';
    std::copy(v.begin(), v.end(), std::ostream_iterator<T>(out, ", "));
    out << "\b\b]";
  }
  return out;
}
```

I think this is dead debugging code (committed by @krenzls in 3f167b5ce0) and should be removed. The usage of backspaces is at the very least dilettantish, leading to very hard-to-find bugs when parsing the output (because it looks right on the terminal).

**Comment by valentjn** [comment]
In GitLab by @krenzls on Aug 15, 2018, 15:07

Yes, this was debugging code and it wasn't my intention to include this.
Apparently it slipped through the rigorous code review process.

By the way: The backspaces make sense for terminal output but is not ideal for parsing.
So I'd rather call it "appropriate for my use-case" not "at the very least dilettantish".

**Comment by valentjn** [comment]
In GitLab by @valentjn on Aug 15, 2018, 15:27

In terminal output, usually, you don't care about trailing commas, if it's just eye candy for debugging. Many languages like C++, Python, and MATLAB also allow trailing commas. So it shouldn't be necessary in most cases to remove the comma (if you want to, use a loop). It looked perfectly fine on the terminal, so I was quite a bit puzzled (copy-and-paste out of the terminal of course doesn't copy the backspaces). IMO "works-for-me" and "dilettantish" are not mutually exclusive. Since this is already in production/release code and SG++ users won't know that this is just debugging code, I'll stick with that term, sorry.

But thanks for the confirmation that this can be removed.

Edit: And yes, it's also my fault, since I did miss it during the merge of !6.

**Comment by valentjn** [comment]
In GitLab by @krenzls on Aug 15, 2018, 15:33

Yes, I do agree that this should have never made it into production code.
But: I do think that this should have been caught during code review.
Right now you're blaming me for a merge that you yourself approved.

**Comment by valentjn** [comment]
In GitLab by @valentjn on Aug 15, 2018, 15:33

See my edit above :smile:

Edit: Oh, and I'm not blaming you. I'm blaming the code, and once merged, the code belongs to everybody.

**Comment by valentjn** [comment]
In GitLab by @valentjn on Aug 17, 2018, 09:32

mentioned in commit 0e44561e61f659a1ba5619b8b69bd57ab12e2134

**Comment by valentjn** [comment]
In GitLab by @pfluegdk on Aug 19, 2018, 17:38

We're working together, and we're all making mistakes. Let's keep up the good work!

**Comment by valentjn** [comment]
In GitLab by @spc90 on Aug 21, 2018, 09:56

@valentjn What is the status of this issue? If fixed, please mark it so. Thanks!

**Comment by valentjn** [comment]
In GitLab by @valentjn on Aug 22, 2018, 13:19

mentioned in merge request !73

**Comment by valentjn** [comment]
@spc90 I think the code's still in there, so this isn't fixed IMO.

**Comment by spc90** [comment]
Dead code removed. Issue will be closed by a next pull request.
