### ISSUE TITLE
Silent exception does not exit the program and results in segfault down the line

### ISSUE THREAD

**Issue by valentjn** [SGpp/SGpp#72]
In GitLab by @elfeck on Oct 29, 2018, 15:53

# Edit

As pointed out in the comments, the immediate issue has been solved, but it is not desirable that exceptions fail silently. This should also be fixed before this issue is resolved.

# Old Issue Description
Title. On current master branch (bad_alloc). Using the CrossValidationExample.json config from the same directory. I made sure the data file is really in the location pointed to by the config.

Valgrind points to [this line](https://simsgs.informatik.uni-stuttgart.de:8444/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/datamining/builder/DataSourceBuilder.cpp#L133) raising the error.

If someone could reproduce this on current master that would be great.

@krsgpp

**Comment by valentjn** [comment]
In GitLab by @elfeck on Oct 29, 2018, 15:53

changed title from **Segfault {-/ bad_alloc-} in datadriven/examplesPipeline/CrossValidationExample** to **Segfault {+(bad_alloc)+} in datadriven/examplesPipeline/CrossValidationExample**

**Comment by valentjn** [comment]
In GitLab by @elfeck on Nov 5, 2018, 11:36

More digging revealed the following:

* [crossValidationAssemble](https://simsgs.informatik.uni-stuttgart.de:8444/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/datamining/builder/DataSourceBuilder.cpp#L107) is manually called by the example (main)
* Because of this manual call file extension detection is not automatically called and  [this exception case is entered](https://simsgs.informatik.uni-stuttgart.de:8444/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/datamining/builder/DataSourceBuilder.cpp#L121) and the exception is thrown
* The exception does not cause the program to stop or fail, so the [SampleProvider pointer](https://simsgs.informatik.uni-stuttgart.de:8444/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/datamining/builder/DataSourceBuilder.cpp#L114)
gets passed along as a `nullptr` and after many intermediate calls leads to an segfault when the pointer is read

Issues:
* The example manually calls `crossValidationAssemble` without proper setup (ultimate cause of the segfaut)
* The exception does apparently not do its job and the error is silent

**Comment by valentjn** [comment]
In GitLab by @elfeck on Nov 5, 2018, 11:49

Turns out, the example is not meant at all to be called with a config as cmd argument but rather the path to a data set. As such the program failed because ".json" is not a valid data set extension. That explains the general issue I had with this example.

However the following issues still remain:
* `data_exception` still fails silently (is this expected behavior?)
* The program runs without issues, but before exiting it raises

> free(): invalid pointer  
> Aborted (core dumped)

which is probably linked to destruction and release of memory, in particular the destruction of [SparseGridMinerCrossValidation](https://simsgs.informatik.uni-stuttgart.de:8444/SGpp/SGpp/blob/master/datadriven/src/sgpp/datadriven/datamining/base/SparseGridMinerCrossValidation.hpp#L85) and its `unique_ptr` member variable.  
Again, this might be because of the "manual" construction of the DataSource in this example. I'm very uncertain if this sets a good example for the usage of the pipeline in general.

**Comment by valentjn** [comment]
In GitLab by @elfeck on Nov 5, 2018, 12:23

mentioned in merge request !79

**Comment by valentjn** [comment]
In GitLab by @elfeck on Nov 26, 2018, 22:18

changed title from **S{-egfault (bad_alloc) in datadriven/examplesPipeline/CrossValidationExampl-}e** to **S{+ilent exception does not exit the program and results in segfault down the lin+}e**

**Comment by valentjn** [comment]
In GitLab by @elfeck on Nov 26, 2018, 22:18

changed the description

**Comment by leiterrl** [comment]
This is also fixed in #216 
The data_exception was constructed but never actually thrown.
