### ISSUE TITLE
Error in python3 installation ("from from" typo)

### ISSUE THREAD

**Issue by dgreenwald** [SGpp/SGpp#95]
In ```datadriven/python/uq/plot/__init__.py``` there is an accidental line  

```from from  pysgpp.extensions.datadriven.uq.parameters.plot.colors import initialize_plotting_style```

with ```from from``` instead of ```from```. The correct line is:

```from  pysgpp.extensions.datadriven.uq.parameters.plot.colors import initialize_plotting_style```

This prevents successful python installation until fixed.

**Comment by valentjn** [comment]
Confirmed. This is fixed in #94 (e84d895), which should be merged soon.
